db_field_mapper = {
    'stanNaDzien': 'record_date',
    'nazwaProduktu': 'product_name',
    'rodzajPreparatu': 'product_type',
    'nazwaPowszechnieStosowana': 'inn_name',
    'moc': 'strength',
    'postac': 'pharmaceutical_form',
    'podmiotOdpowiedzialny': 'ma_holder',
    'typProcedury': 'procedure_type',
    'numerPozwolenia': 'ma_number',
    'waznoscPozwolenia': 'ma_validity',
    'kodATC': 'atc_code1',
    'id': 'id_prod',
    'status': 'status',
    'wielkosc': 'pack_size',
    'jednostkaWielkosci': 'unit',
    'kodEAN': 'ean_14',
    'kategoriaDostepnosci': 'availability_cat',
    'skasowane': 'canceled',
    'numerEu': 'eu_number',
    'dystrybutorRownolegly': 'paralell_importer',
    'id_pack': 'id_pack',
    'substancjaCzynna': 'active_substance',
}
