# Generated by Django 3.1.2 on 2020-10-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('data_downloader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingauthorisation',
            name='ma_validity',
            field=models.DateField(null=True),
        ),
    ]
