# Generated by Django 3.1.2 on 2020-10-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('data_downloader', '0002_auto_20201027_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingauthorisation',
            name='ma_validity',
            field=models.DateField(default=9999),
            preserve_default=False,
        ),
    ]
